[build]
  publish = "dist"
  command = "npx nue build -p"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Optional: Custom redirects
# [[redirects]]
#   from = "/old-page"
#   to = "/new-page"
#   status = 301
